// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/customer/orderaction/order_action.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/customer/orderaction/order_action.go -destination=internal/domain/customer/orderaction/order_action_mock.go -package=orderaction
//

// Package orderaction is a generated GoMock package.
package orderaction

import (
	context "context"
	reflect "reflect"
	time "time"

	button "github.com/Mikhalevich/tg-coffee-shop-bot/internal/domain/messageprocessor/button"
	currency "github.com/Mikhalevich/tg-coffee-shop-bot/internal/domain/port/currency"
	msginfo "github.com/Mikhalevich/tg-coffee-shop-bot/internal/domain/port/msginfo"
	order "github.com/Mikhalevich/tg-coffee-shop-bot/internal/domain/port/order"
	product "github.com/Mikhalevich/tg-coffee-shop-bot/internal/domain/port/product"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageSender is a mock of MessageSender interface.
type MockMessageSender struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSenderMockRecorder
	isgomock struct{}
}

// MockMessageSenderMockRecorder is the mock recorder for MockMessageSender.
type MockMessageSenderMockRecorder struct {
	mock *MockMessageSender
}

// NewMockMessageSender creates a new mock instance.
func NewMockMessageSender(ctrl *gomock.Controller) *MockMessageSender {
	mock := &MockMessageSender{ctrl: ctrl}
	mock.recorder = &MockMessageSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSender) EXPECT() *MockMessageSenderMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessageSender) DeleteMessage(ctx context.Context, chatID msginfo.ChatID, messageID msginfo.MessageID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, chatID, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageSenderMockRecorder) DeleteMessage(ctx, chatID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageSender)(nil).DeleteMessage), ctx, chatID, messageID)
}

// EditMessage mocks base method.
func (m *MockMessageSender) EditMessage(ctx context.Context, chatID msginfo.ChatID, messageID msginfo.MessageID, text string, rows ...button.ButtonRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, messageID, text}
	for _, a := range rows {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EditMessage", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMessage indicates an expected call of EditMessage.
func (mr *MockMessageSenderMockRecorder) EditMessage(ctx, chatID, messageID, text any, rows ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, messageID, text}, rows...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMessage", reflect.TypeOf((*MockMessageSender)(nil).EditMessage), varargs...)
}

// EscapeMarkdown mocks base method.
func (m *MockMessageSender) EscapeMarkdown(s string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EscapeMarkdown", s)
	ret0, _ := ret[0].(string)
	return ret0
}

// EscapeMarkdown indicates an expected call of EscapeMarkdown.
func (mr *MockMessageSenderMockRecorder) EscapeMarkdown(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EscapeMarkdown", reflect.TypeOf((*MockMessageSender)(nil).EscapeMarkdown), s)
}

// ReplyTextMarkdown mocks base method.
func (m *MockMessageSender) ReplyTextMarkdown(ctx context.Context, chatID msginfo.ChatID, replyMessageID msginfo.MessageID, text string, rows ...button.ButtonRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, replyMessageID, text}
	for _, a := range rows {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReplyTextMarkdown", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplyTextMarkdown indicates an expected call of ReplyTextMarkdown.
func (mr *MockMessageSenderMockRecorder) ReplyTextMarkdown(ctx, chatID, replyMessageID, text any, rows ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, replyMessageID, text}, rows...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyTextMarkdown", reflect.TypeOf((*MockMessageSender)(nil).ReplyTextMarkdown), varargs...)
}

// ReplyTextPlain mocks base method.
func (m *MockMessageSender) ReplyTextPlain(ctx context.Context, chatID msginfo.ChatID, replyMessageID msginfo.MessageID, text string, rows ...button.ButtonRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, replyMessageID, text}
	for _, a := range rows {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReplyTextPlain", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplyTextPlain indicates an expected call of ReplyTextPlain.
func (mr *MockMessageSenderMockRecorder) ReplyTextPlain(ctx, chatID, replyMessageID, text any, rows ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, replyMessageID, text}, rows...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyTextPlain", reflect.TypeOf((*MockMessageSender)(nil).ReplyTextPlain), varargs...)
}

// SendTextPlain mocks base method.
func (m *MockMessageSender) SendTextPlain(ctx context.Context, chatID msginfo.ChatID, text string, rows ...button.ButtonRow) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, chatID, text}
	for _, a := range rows {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendTextPlain", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTextPlain indicates an expected call of SendTextPlain.
func (mr *MockMessageSenderMockRecorder) SendTextPlain(ctx, chatID, text any, rows ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, chatID, text}, rows...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTextPlain", reflect.TypeOf((*MockMessageSender)(nil).SendTextPlain), varargs...)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetCurrencyByID mocks base method.
func (m *MockRepository) GetCurrencyByID(ctx context.Context, id currency.ID) (*currency.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrencyByID", ctx, id)
	ret0, _ := ret[0].(*currency.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrencyByID indicates an expected call of GetCurrencyByID.
func (mr *MockRepositoryMockRecorder) GetCurrencyByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrencyByID", reflect.TypeOf((*MockRepository)(nil).GetCurrencyByID), ctx, id)
}

// GetOrderByChatIDAndStatus mocks base method.
func (m *MockRepository) GetOrderByChatIDAndStatus(ctx context.Context, id msginfo.ChatID, statuses ...order.Status) (*order.Order, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range statuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderByChatIDAndStatus", varargs...)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByChatIDAndStatus indicates an expected call of GetOrderByChatIDAndStatus.
func (mr *MockRepositoryMockRecorder) GetOrderByChatIDAndStatus(ctx, id any, statuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, statuses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByChatIDAndStatus", reflect.TypeOf((*MockRepository)(nil).GetOrderByChatIDAndStatus), varargs...)
}

// GetOrderByID mocks base method.
func (m *MockRepository) GetOrderByID(ctx context.Context, id order.ID) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", ctx, id)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockRepositoryMockRecorder) GetOrderByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockRepository)(nil).GetOrderByID), ctx, id)
}

// GetOrderPositionByStatus mocks base method.
func (m *MockRepository) GetOrderPositionByStatus(ctx context.Context, id order.ID, statuses ...order.Status) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range statuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrderPositionByStatus", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderPositionByStatus indicates an expected call of GetOrderPositionByStatus.
func (mr *MockRepositoryMockRecorder) GetOrderPositionByStatus(ctx, id any, statuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, statuses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderPositionByStatus", reflect.TypeOf((*MockRepository)(nil).GetOrderPositionByStatus), varargs...)
}

// GetOrdersCountByStatus mocks base method.
func (m *MockRepository) GetOrdersCountByStatus(ctx context.Context, statuses ...order.Status) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range statuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrdersCountByStatus", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersCountByStatus indicates an expected call of GetOrdersCountByStatus.
func (mr *MockRepositoryMockRecorder) GetOrdersCountByStatus(ctx any, statuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, statuses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersCountByStatus", reflect.TypeOf((*MockRepository)(nil).GetOrdersCountByStatus), varargs...)
}

// GetProductsByIDs mocks base method.
func (m *MockRepository) GetProductsByIDs(ctx context.Context, ids []product.ProductID, currencyID currency.ID) (map[product.ProductID]product.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsByIDs", ctx, ids, currencyID)
	ret0, _ := ret[0].(map[product.ProductID]product.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsByIDs indicates an expected call of GetProductsByIDs.
func (mr *MockRepositoryMockRecorder) GetProductsByIDs(ctx, ids, currencyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsByIDs", reflect.TypeOf((*MockRepository)(nil).GetProductsByIDs), ctx, ids, currencyID)
}

// IsNotFoundError mocks base method.
func (m *MockRepository) IsNotFoundError(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNotFoundError", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNotFoundError indicates an expected call of IsNotFoundError.
func (mr *MockRepositoryMockRecorder) IsNotFoundError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNotFoundError", reflect.TypeOf((*MockRepository)(nil).IsNotFoundError), err)
}

// IsNotUpdatedError mocks base method.
func (m *MockRepository) IsNotUpdatedError(err error) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNotUpdatedError", err)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNotUpdatedError indicates an expected call of IsNotUpdatedError.
func (mr *MockRepositoryMockRecorder) IsNotUpdatedError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNotUpdatedError", reflect.TypeOf((*MockRepository)(nil).IsNotUpdatedError), err)
}

// UpdateOrderByChatAndID mocks base method.
func (m *MockRepository) UpdateOrderByChatAndID(ctx context.Context, orderID order.ID, chatID msginfo.ChatID, data order.UpdateOrderData, prevStatuses ...order.Status) (*order.Order, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orderID, chatID, data}
	for _, a := range prevStatuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrderByChatAndID", varargs...)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderByChatAndID indicates an expected call of UpdateOrderByChatAndID.
func (mr *MockRepositoryMockRecorder) UpdateOrderByChatAndID(ctx, orderID, chatID, data any, prevStatuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orderID, chatID, data}, prevStatuses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderByChatAndID", reflect.TypeOf((*MockRepository)(nil).UpdateOrderByChatAndID), varargs...)
}

// UpdateOrderStatusByChatAndID mocks base method.
func (m *MockRepository) UpdateOrderStatusByChatAndID(ctx context.Context, orderID order.ID, chatID msginfo.ChatID, operationTime time.Time, newStatus order.Status, prevStatuses ...order.Status) (*order.Order, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, orderID, chatID, operationTime, newStatus}
	for _, a := range prevStatuses {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrderStatusByChatAndID", varargs...)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrderStatusByChatAndID indicates an expected call of UpdateOrderStatusByChatAndID.
func (mr *MockRepositoryMockRecorder) UpdateOrderStatusByChatAndID(ctx, orderID, chatID, operationTime, newStatus any, prevStatuses ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, orderID, chatID, operationTime, newStatus}, prevStatuses...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrderStatusByChatAndID", reflect.TypeOf((*MockRepository)(nil).UpdateOrderStatusByChatAndID), varargs...)
}

// MockTimeProvider is a mock of TimeProvider interface.
type MockTimeProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTimeProviderMockRecorder
	isgomock struct{}
}

// MockTimeProviderMockRecorder is the mock recorder for MockTimeProvider.
type MockTimeProviderMockRecorder struct {
	mock *MockTimeProvider
}

// NewMockTimeProvider creates a new mock instance.
func NewMockTimeProvider(ctrl *gomock.Controller) *MockTimeProvider {
	mock := &MockTimeProvider{ctrl: ctrl}
	mock.recorder = &MockTimeProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeProvider) EXPECT() *MockTimeProviderMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockTimeProvider) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockTimeProviderMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockTimeProvider)(nil).Now))
}
