log_level: "info"
tracing:
  endpoint: "jaeger:4318"
  service_name: "msgconsumer"
bot:
  token: "bot token"
  payment_token: "payment token"
postgres:
  connection: "host=postgres port=5432 user=bot password=bot dbname=bot sslmode=disable"
kafka:
  brokers:
    - localhost:9092
  topic: "debezium.public.outbox_messages"
  consumer_group: "group_outbox_messages"
  workers_count: 4